### ISSUE TITLE
UndefVarError when using ThreeQ.Model()

### ISSUE THREAD

**Issue by vkatariya8** [omalled/ThreeQ.jl#1]
Hi, I'm trying to run the canada.jl example and when I use 

`include(canada.jl)`

I get an error

> ERROR: LoadError: UndefVarError: Model not defined

in line 3 of the script, which probably means that there is something wrong with the way ThreeQ.Model() is being executed. Anything I need to fix?

**Comment by omalled** [comment]
I'm not sure what the issue is -- I don't get this error when I run it. However, I am using the version [here](https://github.com/lanl/ThreeQ.jl). Can you try that version and see if you get the same error? If you still get an error, can you copy/paste everything you type and all the output starting from a fresh julia session?

**Comment by vkatariya8** [comment]
I ran it again after reinstalling Julia. It prompted me to install a few packages and it works now. Thank you! 

(using the version that you've linked to)
